### ISSUE TITLE
internal links broken by pandoc update

### ISSUE THREAD

**Issue by mclearc** [liob/pandoc_reader#8]
Has there been some issue of breakage of relative links with pandoc 1.15.1.1? Now links using relative `{filename}/path/to/file` syntax are now all broken. Instead I get `Unable to find '%7Bfilename%7D/path/to/file' or variations`. If not, then something has gone wonky with my set-up.

**Comment by liob** [comment]
I do not know of any changes relevant to this issue. Unfortunately, I will be busy till next Tuesday. Please keep me up to date.

**Comment by mclearc** [comment]
I think I've figured out the problem. Starting with `pandoc 1.15.1` there was a change in the way the HTML writer percent encoded some characters. From the release notes:

> Percent-encode more special characters in URLs (#1640, #2377). The special characters are >'<','>','|','"','{','}','[',']','^', '`'.

This seems to have broken the ability of `pandoc_reader` to read the `{filename}` part of the path in internal links. Until this is fixed it is best to use `pandoc 1.15.0.6` or earlier.

**Comment by mclearc** [comment]
Any idea whether there is a fix for this?

**Comment by spitis** [comment]
An easy fix is to add the following line right before the return statement of the `read` method of the `PandocReader` class in `pandoc_reader.py`:

```
    output = output.replace('%7Bfilename%7D','{filename}')
```

**Comment by mclearc** [comment]
That works. Thanks!
